// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmwnmyfvpdzlahrawlmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtd25teWZ2cGR6bGFocmF3bG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTc2NjcsImV4cCI6MjA3MzM5MzY2N30.GaDyN4eGONFywMHgYjWdG_npNS5zOi6Hv1LMTp0qmB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});